# -*- coding: utf-8 -*-
"""Enhanced_Thermal_Map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDjpl54juwG91FMT4be-tyQTBb4plJw-
"""

import numpy as np
import random
import cmath
import math
import cv2

seed = 42
random.seed(seed)
np.random.seed(seed)

class ThermalMap:

    def __init__(self, seed = 42, length = 100,
                 width = 20, FOV = [55,35],
                 resolution = [32 , 24],
                 pixel_density = 100, time = 13,
                 depth_mine = 0.05,
                 sensor_accuracy=0.01,  # NEW: The +/- range (e.g., +/- 1.0 C)
                 sensor_bit_depth=None # NEW: Optional, e.g., 0.1 means steps of 0.1C
                 ):

        self.conditions = [0,1,2]

        self.width  = width
        self.length = length
        self.time   = time
        self.FOV    = FOV
        self.res    = resolution

        self.pixel_density                = pixel_density
        self.depth_mine                   = depth_mine

        random.seed(seed)
        np.random.seed(seed)

        self.pixel_len   = pixel_density*self.length
        self.pixel_width = pixel_density*self.width

        # INTERPRETATION OF ACCURACY:
        # If a sensor says "+/- 1C", it usually means 95% of readings are within 1C.
        # In a Normal Distribution, 95% is within 2 standard deviations (2*sigma).
        # So, sigma (std_dev) = accuracy / 2
        self.noise_sigma = sensor_accuracy / 2.0

        # If you want to simulate digital steps (e.g., 0.1C resolution)
        self.quantization_step = sensor_bit_depth

        # Calculating Thermal Values
        #-----------------------------------------------------------------------------------------------------------------
        T_mean         = 28                              #T_mean is the long-term average temperature over many days/cycles,
                                                         #Here T_mean is assumed to be average air temperature over the year.

        self.omega          = (2*math.pi)/(86400)             #Sun's angular freq
        self.Q0             = 180                             #Solar Flux amps
        self.t_sec          = (self.time - 12)*3600           #Seconds from solar noon
        self.phase_base     = -1*math.pi/4

        # No anomaly Condition Should run for all of them

        k_s     = 1.0                              #Soil Conductivity
        pcp_s   = 1.6e6                            #Soil Vol. Heat Capacity
        alpha_s = k_s/(pcp_s)                      #Soil Diffusivity
        self.Z_s     = 1/cmath.sqrt(1j*self.omega*k_s*pcp_s) #Soil Impedence
        self.delta   = math.sqrt(2*alpha_s/self.omega)       #Skin Depth
        self.gamma   = (1 + 1j)/self.delta                   #propogation Constant
        self.A       = self.Q0*abs(self.Z_s)

        T_soil_surface = T_mean + self.A*math.cos(self.omega*self.t_sec + self.phase_base)

        self.T_base            = T_soil_surface
        #-----------------------------------------------------------------------------------------------------------------

        self.grid = np.full([self.pixel_len, self.pixel_width],self.T_base)

    def Thermal_Calculations(self, condition = 0, depth_z = 0.01):
        # condition parameter decides which anomaly is present
        # 0 -> No anomaly
        # 1 -> Mines/Plastic : We will assume case for PVC
        # 2 -> Buried Rocks

        if (condition not in self.conditions): raise ValueError("Condition value should be from [0,1,2]")
        Surface_temperature = {}

        omega          = self.omega              #Sun's angular freq
        Q0             = self.Q0                 #Solar Flux amps
        t_sec          = self.t_sec              #Seconds from solar noon
        phase_base     = self.phase_base

        # No anomaly Condition Should run for all of them

        Z_s   = self.Z_s
        delta = self.delta
        gamma = self.gamma
        A     = self.A


        if condition == 1:
            # Presence of Mines
            depth = depth_z
            k_m   = 0.28
            pcp_m = 1.8e6

            Z_m           = 1/cmath.sqrt(1j*omega*k_m*pcp_m)
            gamma_complex = (Z_m - Z_s)/(Z_m + Z_s)
            atten         = math.exp(-2*depth/delta)
            phase_anomaly = -2*depth/delta

            delta_T_anom = A*abs(gamma_complex)*atten*math.cos(omega*t_sec + phase_anomaly + phase_base)

            self.T_anomaly_delta_peak = delta_T_anom

            # Realism Correction:
            # Small objects lose heat sideways.
            # A 0.7 factor roughly approximates this 3D loss for standard anti-personnel mines.
            shape_factor = 0.7

            return delta_T_anom * shape_factor

        elif condition == 2:
            # Presence of Rocks
            if depth_z > 0.02:
                k_rock   = 2.8
                pcp_rock = 2.2e6

                Z_rock        = 1/cmath.sqrt(1j*omega*k_rock*pcp_rock)
                gamma_complex = (Z_rock - Z_s)/(Z_rock + Z_s)
                atten         = math.exp(-2*depth_z/delta)
                phase_anomaly = -2*depth_z/delta

                delta_T_rocks = A*abs(gamma_complex)*atten*math.cos(omega*t_sec + phase_anomaly + phase_base)
                return delta_T_rocks

            else:
                delta_T_rocks = 10 + random.uniform(-2.0,1.0)
                return delta_T_rocks

        return


    def sigmoidal_function(self, std = 1, xd = 1 ,r=0):
        # xd is decay rate how fast it goes from 0 to 1
        # std is size of flatness distance between both solutions for y=0.5
        a = 4*3.4534/xd
        b = a*std/2
        return 1/(1 + np.exp(a*r - b)) - 1/(1 + np.exp(a*r + b))

    def add_object(self, x_meter, y_meter, spread_x = 1, spread_y = 1, rotation_deg = 30, radius_px=30, is_mine = 0, depth_z = 0.05):

        center_x_pixel = int(x_meter*self.pixel_density)
        center_y_pixel = int(y_meter*self.pixel_density)
        radius_px      = int(radius_px)

        # Creation of patch
        margin = int(self.pixel_density * 0.5) # 0.5 meter margin, for example
        patch_size = radius_px + margin
        x,y = np.ogrid[-patch_size:patch_size, -patch_size:patch_size]

        # Rotation of the object
        theta = np.radians(rotation_deg)
        x_rot = x*np.cos(theta) - y*np.sin(theta)
        y_rot = x*np.sin(theta) + y*np.cos(theta)

          # Calculate Bounds (Clipping safe)
        start_x = max(0, center_x_pixel - patch_size)
        start_y = max(0, center_y_pixel - patch_size)
        end_x = min(self.pixel_width, center_x_pixel + patch_size)
        end_y = min(self.pixel_len, center_y_pixel + patch_size)

        # Calculate Stamp Offsets
        stamp_start_x = 0 if start_x == center_x_pixel - patch_size else (patch_size - (center_x_pixel - start_x))
        stamp_start_y = 0 if start_y == center_y_pixel - patch_size else (patch_size - (center_y_pixel - start_y))
        stamp_end_x = stamp_start_x + (end_x - start_x)
        stamp_end_y = stamp_start_y + (end_y - start_y)



        #Heat patch Guassian and Sigmoidal
        if is_mine:
            r_px   = np.sqrt(x**2 + y**2)
            #std - xd = radius
            xd_px = self.pixel_density * 0.2  # Moderate fade
            std_px = 2 * radius_px

            delta_temp_mine = self.Thermal_Calculations(condition = 1)
            heat_patch = delta_temp_mine * self.sigmoidal_function(std = std_px, xd = xd_px, r = r_px)

            self.grid[start_y:end_y, start_x:end_x] += heat_patch[stamp_start_y:stamp_end_y, stamp_start_x:stamp_end_x]

        else:

            delta_temp = self.Thermal_Calculations(condition = 2, depth_z = depth_z)
            heat_patch = delta_temp*np.exp(-1*(x_rot**2/spread_x + y_rot**2/spread_y))

            self.grid[start_y:end_y, start_x:end_x] += heat_patch[stamp_start_y:stamp_end_y, stamp_start_x:stamp_end_x]

    def add_mine(self, x_meter_mine, y_meter_mine, mine_radius):

        print(f"Adding Mine at ({x_meter_mine},{y_meter_mine}) ...")
        depth  = self.depth_mine
        depth += random.uniform(-0.2,0.2)

        self.add_object(x_meter= x_meter_mine, y_meter= y_meter_mine,
                        radius_px = mine_radius*self.pixel_density, is_mine = 1, depth_z=depth)
        print(f"Mine added sucessfully.")

    def add_anomaly(self, count_surface = 10, count_underground = 20):

        print(f"Preparing to add {count_surface} surface anomalies...")
        for i in range(count_surface):

            x_meters = random.uniform(0.001*self.width, 0.998*self.width)
            y_meters = random.uniform(0.001*self.length, 0.998*self.length)

            base_rock_px  = random.uniform(1.0,10.0)   #Rocks size from 1cm to 10cm
            spread_rock   = random.uniform(1.0,3.0)    #Direction spread factor

            if random.choice([True,False]):
                spreadx, spready = base_rock_px*spread_rock, base_rock_px
            else:
                spreadx, spready = base_rock_px, base_rock_px*spread_rock

            depth = 0
            angle = random.uniform(0,360)

            self.add_object(x_meter = x_meters, y_meter = y_meters,spread_x = spreadx,
                            spread_y = spready, depth_z = depth, rotation_deg = angle)

        print(f"Added {count_surface} surface anomalies successfully \n")

        print(f"Preparing to add {count_underground} surface anomalies...")
        for i in range(count_underground):

            x_meters = random.uniform(0.001*self.width, 0.998*self.width)
            y_meters = random.uniform(0.001*self.length, 0.998*self.length)

            base_rock_px  = random.uniform(1.0,10.0)   #Rocks size from 1cm to 10cm
            spread_rock = random.uniform(1.0,3.0)    #Direction spread factor

            if random.choice([True,False]):
                spreadx, spready = base_rock_px*spread_rock, base_rock_px
            else:
                spreadx, spready = base_rock_px, base_rock_px*spread_rock

            depth = random.uniform(0.02,0.15)
            angle = random.uniform(0,360)

            self.add_object(x_meter = x_meters, y_meter = y_meters,spread_x = spreadx,
                            spread_y = spready, depth_z = depth, rotation_deg = angle)
        print(f"Added {count_underground} surface anomalies successfully")


    def get_view(self, drone_x, drone_y, drone_height):

        fov_horz_rad, fov_vert_rad = self.FOV
        fov_horz_rad = math.radians(fov_horz_rad)
        fov_vert_rad = math.radians(fov_vert_rad)

        ground_view_hor = 2 * drone_height * math.tan(fov_horz_rad / 2)
        ground_view_ver = 2 * drone_height * math.tan(fov_vert_rad / 2)

        section_slice_x = int(ground_view_hor * self.pixel_density)
        section_slice_y = int(ground_view_ver * self.pixel_density)

        half_slice_x    = section_slice_x // 2
        half_slice_y    = section_slice_y // 2

        drone_x_px = int(drone_x * self.pixel_density)
        drone_y_px = int(drone_y * self.pixel_density)

        start_x    = max(0, drone_x_px - half_slice_x)
        start_y    = max(0, drone_y_px - half_slice_y)

        end_x      = min(self.pixel_width, drone_x_px + half_slice_x)
        end_y      = min(self.pixel_len, drone_y_px + half_slice_y)

        map_section = self.grid[start_y:end_y,start_x:end_x]

        if map_section.shape != (section_slice_x, section_slice_y):

            padded = np.full((section_slice_y, section_slice_x), self.T_base)

            #----------------------------------------------------------------------------------
            # The idea here is that when drone moves near edge of the map it should still receive
            # full image input in real life, but here we are going out of the array so all outer
            # border of array needs to give padded output for such cases.
            #----------------------------------------------------------------------------------

            ideal_start_x = drone_x_px - half_slice_x
            ideal_start_y = drone_y_px - half_slice_y

            height, width = map_section.shape
            start_loc_x   = abs(start_x - ideal_start_x)
            start_loc_y   = abs(start_y - ideal_start_y)

            padded[start_loc_y:start_loc_y + height, start_loc_x:start_loc_x + width] = map_section

            map_section = padded

        sensor_res_x, sensor_res_y = self.res

        sensor_view = cv2.resize(map_section, (sensor_res_x, sensor_res_y), interpolation=cv2.INTER_AREA)
        # 1. Add Random Noise (NETD)
        # We use the sigma calculated from your "+/- 1C" requirement
        sensor_noise = np.random.normal(0, self.noise_sigma, (sensor_res_y, sensor_res_x))
        sensor_view += sensor_noise

        # If your sensor can only read in 0.5C steps, 28.3C becomes 28.5C
        if self.quantization_step is not None:
            sensor_view = np.round(sensor_view / self.quantization_step) * self.quantization_step

        sensor_view = np.clip(sensor_view, -20, 150)

        sensor_view += sensor_noise

        return sensor_view

import numpy as np
import matplotlib.pyplot as plt

def sigmoidal_function(std=1, xd=1, r=0):
    # a determines the steepness (decay rate)
    a = 4 * 3.4534 / xd
    # b determines the offset/width of the flat region
    b = a * std / 2
    return 1/(1 + np.exp(a * r - b)) - 1/(1 + np.exp(a * r + b))

radius_px = 30
xd_px = 40
std_px = radius_px + xd_px

# Create coordinate grid
x, y = np.ogrid[-radius_px:radius_px, -radius_px:radius_px]
r_px = np.sqrt(x**2 + y**2)

# Generate the patch
heat_patch = 3 * sigmoidal_function(std=std_px, xd=xd_px, r=r_px)

# --- Visualization ---
fig, ax = plt.subplots(1, 2, figsize=(12, 5))

# 1. Heatmap visualization
im = ax[0].imshow(heat_patch, cmap='magma', extent=[-radius_px, radius_px, -radius_px, radius_px])
ax[0].set_title("2D Heat Patch (Sigmoidal)")
fig.colorbar(im, ax=ax[0], label='Intensity')

# 2. 1D Slice (Cross-section through the center)
# This helps verify the 'std' (flatness) and 'xd' (decay)
center_line = heat_patch[radius_px, :]
ax[1].plot(np.linspace(-radius_px, radius_px, len(center_line)), center_line)
ax[1].set_title("1D Cross-section Profile")
ax[1].set_xlabel("Radius (px)")
ax[1].set_ylabel("Value")
ax[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import cv2

# 1. Initialize the Simulation
print("Initializing Map...")
sim = ThermalMap(length=100, width=50, pixel_density=20) # Lower density for faster test

# 2. Add Anomalies (The "Physics" Test)
# Add a mine near the center
sim.add_mine(x_meter_mine=25, y_meter_mine=50, mine_radius=0.25)

# Add some random rocks
sim.add_anomaly(count_surface=25, count_underground=25)

# 3. Add a Mine specifically at the EDGE (The "Slicing" Test)
# We put a mine at x=1, y=1 (Top-Left corner) to see if we can view it
sim.add_mine(x_meter_mine=1.0, y_meter_mine=1.0, mine_radius=0.3)

# ==========================================
# VISUALIZATION
# ==========================================
fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(18, 6))

# --- PLOT 1: The Full Ground Truth Map ---
# This checks if your Gaussian spots and Physics math created a map
c1 = ax1.imshow(sim.grid, cmap='inferno', origin='upper')
ax1.set_title("Full Ground Truth Map (Top-Down)")
plt.colorbar(c1, ax=ax1, fraction=0.046, pad=0.04)

# --- PLOT 2: The "Center" View ---
# Drone looking at the mine in the middle. Should be a clean crop.
view_center = sim.get_view(drone_x=25, drone_y=50, drone_height=1)
ax2.imshow(view_center, cmap='inferno', origin='upper')
ax2.set_title("Drone View: Center (Safe Case)")

# --- PLOT 3: The "Edge" View (The Logic Test) ---
# Drone hovering at (0,0).
# If your padding logic works, you should see the mine in the corner
# and the rest should be 'flat' background temperature (the padding).
view_edge = sim.get_view(drone_x=0, drone_y=0, drone_height=3)
ax3.imshow(view_edge, cmap='inferno', origin='upper')
ax3.set_title("Drone View: Edge (0,0) (Logic Test)")

plt.tight_layout()
plt.show()

