"""
tcp_commander.py  —  Master → Slave Command Dispatch over TCP
=============================================================
Architecture
------------
• Each slave runs a small TCP server (listen on its own IP : CMD_PORT).
• The master maintains ONE persistent TCP connection per slave.
  Connections are created at startup and automatically reconnected on drop.
• Commands from two sources feed into per-slave asyncio.Queues:
    - Voice commands   (via STATE.pending_voice_cmd, polled from app.py)
    - Waypoint GOTOs   (generated by the path planner in this file)
• A dispatcher coroutine per slave drains its queue and sends commands
  over its TCP connection.  All three dispatchers run concurrently via
  asyncio.gather(), so all slaves receive their commands simultaneously —
  not one-at-a-time.

Why persistent connections?
  • Reconnect overhead of TCP handshake is avoided between commands.
  • The slave always has a live socket ready; there's no window where a
    command could be lost because the connection wasn't up yet.
  • TCP gives us ordered, reliable delivery — if we send GOTO then SCAN,
    the slave receives them in that order, confirmed.

Command protocol (master → slave, over TCP)
-------------------------------------------
Newline-delimited JSON.  Each command is one JSON object terminated by \n.

  GOTO waypoint:
  { "cmd": "GOTO", "lat": 12.9716, "lng": 77.5946, "alt": 3.0, "seq": 7 }

  Voice/mission commands:
  { "cmd": "START" | "PAUSE" | "RESUME" | "LAND" | "SCAN" }

  Acknowledgement (slave → master, same connection):
  { "ack": "GOTO", "seq": 7, "status": "ok" | "rejected" }

Collision-safe waypoint dispatch
---------------------------------
Before sending any GOTO to slave_X:
  1. Take a snapshot of all drone positions (outside the lock).
  2. Call STATE.find_safe_waypoint(desired_x, desired_y, "slave_X").
  3. If a safe waypoint exists (possibly nudged), convert back to GPS and send.
  4. If no safe point found within search radius, defer the command 0.5 s
     and retry up to MAX_RETRIES times, then send a HOLD command instead.

How simultaneous commands work
------------------------------
Scenario: slave_1 and slave_2 both need to move to new waypoints.
  • Path planner pushes GOTO_A into slave_1's queue.
  • Path planner pushes GOTO_B into slave_2's queue.
  • _dispatcher("slave_1") and _dispatcher("slave_2") are running as
    separate asyncio Tasks.
  • Both tasks drain their queues concurrently — they don't wait for
    each other.  From the slaves' perspective, the commands arrive at
    nearly the same instant (within a few milliseconds).
  • The collision check for slave_1 already excludes slave_2's current
    position, and vice versa, so both waypoints are guaranteed safe
    relative to each other at the time of planning.
"""

import asyncio
import json
import logging
import math
import time
from typing import Optional

from swarm_state import STATE, DRONE_IDS, SAFE_SEP_M, MINE_CLEAR_M

# ════════════════════════════════════════════════════════════════════════════
#  CONFIG
# ════════════════════════════════════════════════════════════════════════════
CMD_PORT          = 14560        # all slaves listen on this port
RECONNECT_DELAY_S = 3.0          # wait before retrying a dropped connection
ACK_TIMEOUT_S     = 2.0          # wait for COMMAND_ACK before retry
MAX_CMD_RETRIES   = 3            # retransmit unACKed commands this many times
WAYPOINT_RETRY_S  = 0.5          # retry interval when no safe waypoint found
MAX_WP_RETRIES    = 6            # give up after this many waypoint retries

# Slave hostnames/IPs on the drone Wi-Fi network.
# Master connects TO these.
SLAVE_ADDRS: dict[str, tuple[str, int]] = {
    "slave_1": ("10.42.0.11", CMD_PORT),   # drone1 — fixed by dnsmasq
    "slave_2": ("10.42.0.12", CMD_PORT),   # drone2
    "slave_3": ("10.42.0.13", CMD_PORT),   # drone3
}

log = logging.getLogger("tcp_commander")
logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(name)s] %(message)s",
    datefmt="%H:%M:%S",
)


# ════════════════════════════════════════════════════════════════════════════
#  CONNECTION WRAPPER  — one per slave
# ════════════════════════════════════════════════════════════════════════════
class SlaveConnection:
    """
    Manages a single persistent TCP connection to one slave drone.

    • Automatically reconnects on drop with exponential back-off.
    • Sends newline-delimited JSON commands.
    • Reads ACK lines from the slave and resolves pending ACK futures.
    """

    def __init__(self, drone_id: str, host: str, port: int):
        self.drone_id = drone_id
        self.host     = host
        self.port     = port

        self._reader: Optional[asyncio.StreamReader]  = None
        self._writer: Optional[asyncio.StreamWriter]  = None
        self._connected = asyncio.Event()

        # Map of seq → Future, resolved when ACK arrives
        self._pending_acks: dict[int, asyncio.Future] = {}
        self._cmd_seq = 0

    @property
    def is_connected(self) -> bool:
        return self._writer is not None and not self._writer.is_closing()

    async def connect_loop(self) -> None:
        """
        Background task: keep the connection alive.
        Retries with a fixed delay on any failure.
        """
        delay = RECONNECT_DELAY_S
        while True:
            try:
                log.info(f"[{self.drone_id}] Connecting to {self.host}:{self.port}…")
                self._reader, self._writer = await asyncio.open_connection(
                    self.host, self.port
                )
                self._connected.set()
                log.info(f"[{self.drone_id}] TCP connected ✓")
                delay = RECONNECT_DELAY_S   # reset back-off on success

                # Read ACKs until the connection drops
                await self._read_acks()

            except (ConnectionRefusedError, OSError, asyncio.TimeoutError) as e:
                log.warning(f"[{self.drone_id}] Connection failed: {e}  — retry in {delay}s")
            except Exception as e:
                log.error(f"[{self.drone_id}] Unexpected error: {e}")

            # Clean up
            self._connected.clear()
            self._writer = None
            self._reader = None

            # Fail all pending ACK futures so callers don't hang
            for fut in self._pending_acks.values():
                if not fut.done():
                    fut.set_result({"ack": "TIMEOUT", "status": "disconnected"})
            self._pending_acks.clear()

            await asyncio.sleep(delay)

    async def _read_acks(self) -> None:
        """Read lines from the slave and resolve pending ACK futures."""
        async for line in self._reader:
            try:
                msg = json.loads(line.decode("utf-8").strip())
            except json.JSONDecodeError:
                continue

            seq = msg.get("seq")
            if seq is not None and seq in self._pending_acks:
                fut = self._pending_acks.pop(seq)
                if not fut.done():
                    fut.set_result(msg)
                log.debug(f"[{self.drone_id}] ACK seq={seq} status={msg.get('status')}")

    async def send_command(self, payload: dict, expect_ack: bool = True) -> dict:
        """
        Send a JSON command and optionally wait for an ACK.
        Returns the ACK dict, or {"status": "timeout"} on timeout.

        Thread-safe: asyncio guarantees serial coroutine execution,
        so concurrent send_command() calls are naturally serialised
        per connection.  Different slave connections run concurrently.
        """
        await self._connected.wait()   # block until connected

        self._cmd_seq += 1
        seq = self._cmd_seq
        payload["seq"] = seq

        line = (json.dumps(payload) + "\n").encode("utf-8")

        if expect_ack:
            loop = asyncio.get_running_loop()   # get_event_loop() deprecated in 3.10+
            ack_future = loop.create_future()
            self._pending_acks[seq] = ack_future

        try:
            self._writer.write(line)
            await self._writer.drain()
            log.info(f"[{self.drone_id}] → {payload['cmd']}  seq={seq}")
        except Exception as e:
            log.error(f"[{self.drone_id}] Send failed: {e}")
            if expect_ack and seq in self._pending_acks:
                del self._pending_acks[seq]
            return {"status": "send_error"}

        if not expect_ack:
            return {"status": "sent"}

        try:
            ack = await asyncio.wait_for(ack_future, timeout=ACK_TIMEOUT_S)
            return ack
        except asyncio.TimeoutError:
            log.warning(f"[{self.drone_id}] ACK timeout seq={seq}")
            self._pending_acks.pop(seq, None)
            return {"status": "timeout"}


# ════════════════════════════════════════════════════════════════════════════
#  COLLISION-SAFE GOTO HELPER
# ════════════════════════════════════════════════════════════════════════════
async def safe_goto(
    conn:      SlaveConnection,
    desired_x: float,
    desired_y: float,
    alt:       Optional[float] = None,
) -> bool:
    """
    Plan and send a collision-safe GOTO command to one slave.

    1. Check if desired waypoint is safe.
    2. If not, nudge outward to find the nearest safe point.
    3. Retry up to MAX_WP_RETRIES if no safe point exists yet (drones moving).
    4. Convert safe (x, y) back to GPS.
    5. Send GOTO with ACK.  Retry up to MAX_CMD_RETRIES if no ACK.
    Returns True on success, False on failure.
    """
    did     = conn.drone_id
    alt_m   = alt if alt is not None else STATE.mission.cruise_alt_m

    # ── Find safe waypoint (retry if currently blocked) ──────────────────
    safe_pos = None
    for attempt in range(MAX_WP_RETRIES):
        with STATE.lock:   # threading.Lock — not async
            safe_pos = STATE.find_safe_waypoint(desired_x, desired_y, did)

        if safe_pos is not None:
            break

        log.warning(
            f"[{did}] No safe waypoint near ({desired_x:.1f},{desired_y:.1f}) "
            f"— attempt {attempt+1}/{MAX_WP_RETRIES}, waiting {WAYPOINT_RETRY_S}s"
        )
        await asyncio.sleep(WAYPOINT_RETRY_S)

    if safe_pos is None:
        log.error(f"[{did}] Could not find safe waypoint — sending HOLD")
        await conn.send_command({"cmd": "HOLD"})
        return False

    sx, sy = safe_pos
    if math.hypot(sx - desired_x, sy - desired_y) > 0.1:
        log.info(f"[{did}] Waypoint nudged ({desired_x:.1f},{desired_y:.1f}) → ({sx:.1f},{sy:.1f})")

    # ── Convert to GPS ────────────────────────────────────────────────────
    lat, lng = STATE.local_to_gps(sx, sy)

    # ── Send with retries ─────────────────────────────────────────────────
    for attempt in range(MAX_CMD_RETRIES):
        ack = await conn.send_command({
            "cmd": "GOTO",
            "lat": lat, "lng": lng, "alt": alt_m,
        })
        if ack.get("status") == "ok":
            log.info(f"[{did}] GOTO confirmed at ({sx:.1f},{sy:.1f})")
            return True
        log.warning(f"[{did}] GOTO not ACKed (attempt {attempt+1}): {ack}")
        await asyncio.sleep(0.2)

    log.error(f"[{did}] GOTO failed after {MAX_CMD_RETRIES} attempts")
    return False


# ════════════════════════════════════════════════════════════════════════════
#  SIMULTANEOUS GOTO DISPATCHER
# ════════════════════════════════════════════════════════════════════════════
async def dispatch_waypoints_simultaneously(
    waypoints: dict[str, tuple[float, float]],
    connections: dict[str, SlaveConnection],
    alt: Optional[float] = None,
) -> dict[str, bool]:
    """
    Send GOTO commands to multiple slaves AT THE SAME TIME.

    waypoints = { "slave_1": (x1, y1), "slave_2": (x2, y2), … }

    asyncio.gather() runs all safe_goto() coroutines concurrently.
    Each slave's collision check accounts for the others' CURRENT positions
    (not their destination), which is the safest conservative approach.

    Returns { "slave_1": True/False, "slave_2": True/False, … }
    """
    tasks = {
        did: asyncio.create_task(
            safe_goto(connections[did], x, y, alt),
            name=f"goto_{did}",
        )
        for did, (x, y) in waypoints.items()
        if did in connections
    }

    results = await asyncio.gather(*tasks.values(), return_exceptions=True)

    return {
        did: (r if isinstance(r, bool) else False)
        for did, r in zip(tasks.keys(), results)
    }


# ════════════════════════════════════════════════════════════════════════════
#  VOICE COMMAND DISPATCHER
# ════════════════════════════════════════════════════════════════════════════
BROADCAST_CMDS = {"START", "PAUSE", "RESUME", "LAND"}   # go to all slaves
MASTER_ONLY_CMDS = {"SCAN", "STATUS"}

async def dispatch_voice_command(
    cmd: str,
    connections: dict[str, SlaveConnection],
) -> None:
    """
    Fan-out a voice command to all (or relevant) slaves simultaneously.
    LAND is always broadcast — never deferred or skipped.
    """
    cmd_upper = cmd.upper()

    if cmd_upper in MASTER_ONLY_CMDS:
        log.info(f"[VOICE] {cmd_upper} is master-only — not forwarded to slaves")
        return

    if cmd_upper not in BROADCAST_CMDS:
        log.warning(f"[VOICE] Unknown command '{cmd_upper}' — ignored")
        return

    log.info(f"[VOICE] Broadcasting {cmd_upper} to all slaves simultaneously")

    # asyncio.gather → all slaves get the command at the same time
    await asyncio.gather(*[
        conn.send_command({"cmd": cmd_upper}, expect_ack=(cmd_upper != "LAND"))
        for conn in connections.values()
    ])

    # Mirror mission state locally
    if cmd_upper == "START":
        with STATE.lock:
            if not STATE.mission.started:
                STATE.mission.started    = True
                STATE.mission.start_time = STATE.mission.start_time or time.time()
    elif cmd_upper == "LAND":
        with STATE.lock:
            STATE.mission.ended = True


# ════════════════════════════════════════════════════════════════════════════
#  PER-SLAVE COMMAND QUEUE DISPATCHER
# ════════════════════════════════════════════════════════════════════════════
async def _queue_dispatcher(
    drone_id:   str,
    conn:       SlaveConnection,
) -> None:
    """
    Drains STATE.cmd_queues[drone_id] and executes each command.
    Runs as a long-lived coroutine alongside every other slave's dispatcher.

    This is where voice commands (pushed by app.py) and planned GOTOs
    (pushed by the path planner) converge and get sent out.

    Because each slave has its OWN queue and its OWN dispatcher coroutine,
    a slow ACK from slave_1 never delays slave_2.
    """
    q = STATE.cmd_queues[drone_id]   # threading queue.Queue (not asyncio)
    log.info(f"[{drone_id}] Queue dispatcher running")
    loop = asyncio.get_running_loop()

    while True:
        # queue.Queue.get() is blocking — run in executor so we don't block the event loop
        item = await loop.run_in_executor(None, q.get)
        cmd  = item.get("cmd", "").upper()

        try:
            if cmd == "GOTO":
                # Waypoint command — run collision-safe dispatch
                await safe_goto(conn, item["x"], item["y"], item.get("alt"))

            elif cmd in BROADCAST_CMDS:
                await conn.send_command({"cmd": cmd})

            elif cmd == "HOLD":
                await conn.send_command({"cmd": "HOLD"}, expect_ack=False)

            else:
                log.warning(f"[{drone_id}] Unknown queued command: {cmd}")

        except Exception as e:
            log.error(f"[{drone_id}] Dispatcher error on {cmd}: {e}")
        finally:
            q.task_done()   # marks queue.Queue item as processed


# ════════════════════════════════════════════════════════════════════════════
#  SLAVE-SIDE: TCP command server (runs ON each slave drone)
# ════════════════════════════════════════════════════════════════════════════
async def slave_command_server(
    drone_id: str,
    host:     str = "0.0.0.0",
    port:     int = CMD_PORT,
) -> None:
    """
    Run this on each slave.
    Accepts ONE connection from the master and processes commands.
    Sends ACKs back on the same connection.

    Replace the stub handler with real MAVSDK calls.
    """

    async def _handle_master(reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
        peer = writer.get_extra_info("peername")
        log.info(f"[{drone_id}] Master connected from {peer}")
        try:
            async for line in reader:
                try:
                    cmd_pkt = json.loads(line.decode("utf-8").strip())
                except json.JSONDecodeError:
                    continue

                cmd = cmd_pkt.get("cmd", "").upper()
                seq = cmd_pkt.get("seq")
                log.info(f"[{drone_id}] ← {cmd}  seq={seq}")

                # ── Execute the command (replace stubs with MAVSDK) ──────
                status = await _execute_command_stub(drone_id, cmd_pkt)
                # ────────────────────────────────────────────────────────

                # Send ACK back to master
                ack = json.dumps({"ack": cmd, "seq": seq, "status": status}) + "\n"
                writer.write(ack.encode("utf-8"))
                await writer.drain()

        except asyncio.IncompleteReadError:
            pass
        finally:
            log.warning(f"[{drone_id}] Master disconnected")
            writer.close()

    server = await asyncio.start_server(_handle_master, host, port)
    log.info(f"[{drone_id}] TCP command server listening on {host}:{port}")
    async with server:
        await server.serve_forever()


async def _execute_command_stub(drone_id: str, pkt: dict) -> str:
    """
    STUB — replace with real MAVSDK calls on each slave.

    Example real implementations:
      GOTO  → await drone.action.goto_location(lat, lng, alt, yaw)
      LAND  → await drone.action.land()
      PAUSE → await drone.action.hold()  (or mission pause)
      START → await drone.action.arm(); await drone.action.takeoff()
    """
    cmd = pkt.get("cmd", "").upper()
    log.info(f"[STUB][{drone_id}] Executing {cmd} {pkt}")
    await asyncio.sleep(0.05)  # simulate execution latency
    return "ok"


# ════════════════════════════════════════════════════════════════════════════
#  MASTER-SIDE ENTRY POINT
# ════════════════════════════════════════════════════════════════════════════
async def start_tcp_commander(
    slave_addrs: dict[str, tuple[str, int]] = SLAVE_ADDRS,
) -> None:
    """
    Start the TCP command subsystem on the master.
    Creates one SlaveConnection per slave, starts connect loops and
    queue dispatchers for each — all running concurrently.

    Example (in master.py):
        await asyncio.gather(
            udp_telemetry.start_udp_server(),
            tcp_commander.start_tcp_commander(),
        )
    """
    connections: dict[str, SlaveConnection] = {}

    for did, (host, port) in slave_addrs.items():
        conn = SlaveConnection(did, host, port)
        connections[did] = conn

        # Connection loop — reconnects automatically on drop
        asyncio.create_task(conn.connect_loop(), name=f"conn_{did}")

        # Per-slave command queue dispatcher
        asyncio.create_task(
            _queue_dispatcher(did, conn),
            name=f"dispatcher_{did}",
        )

    log.info(f"TCP commander ready — managing {list(connections.keys())}")

    # ── Voice command bridge ──────────────────────────────────────────────
    # Poll STATE.pending_voice_cmd (set by the Flask voice API in app.py)
    # and fan it out to all slaves.
    asyncio.create_task(
        _voice_bridge(connections),
        name="voice_bridge",
    )

    # Keep this coroutine alive — it acts as the anchor for the tasks above
    await asyncio.Future()


async def _voice_bridge(connections: dict[str, SlaveConnection]) -> None:
    """
    Polls app.py's /api/pending_commands every 100 ms over HTTP.
    app.py is where the phone streams audio and Vosk recognises intents.
    Commands are consumed on each poll (app.py clears the list on GET).

    Recognised commands:
        start / pause / resume / land  →  broadcast to all slaves
        scan / status                  →  master-only, handled locally

    Falls back gracefully if app.py is not yet up (logs warning, keeps retrying).
    """
    import aiohttp

    APP_URL = "https://10.42.0.1/api/pending_commands"

    # One shared session for the lifetime of the bridge
    connector = aiohttp.TCPConnector(ssl=False)   # self-signed cert on Pi
    session   = aiohttp.ClientSession(connector=connector)

    log.info("[VOICE] Bridge started — polling app.py at 10 Hz")

    try:
        while True:
            await asyncio.sleep(0.1)
            try:
                async with session.get(
                    APP_URL,
                    timeout=aiohttp.ClientTimeout(total=0.4),
                ) as resp:
                    if resp.status != 200:
                        continue
                    data = await resp.json()
                    cmds = data.get("commands", [])

            except Exception as e:
                log.debug(f"[VOICE] app.py poll failed: {e}")
                continue

            for cmd in cmds:
                cmd_upper = cmd.upper()
                log.info(f"[VOICE] Received from app.py: {cmd_upper}")

                # Mirror mission state into STATE so rest of system sees it
                if cmd_upper == "START":
                    with STATE.lock:
                        if not STATE.mission.started:
                            STATE.mission.started    = True
                            STATE.mission.start_time = STATE.mission.start_time or time.time()

                elif cmd_upper in ("LAND", "ABORT"):
                    with STATE.lock:
                        STATE.mission.ended = True

                # Fan out to slaves (SCAN and STATUS are master-only, skip)
                await dispatch_voice_command(cmd_upper, connections)

    finally:
        await session.close()


# ════════════════════════════════════════════════════════════════════════════
#  ORDERED SIDEWAYS MOVE DISPATCHER  (competition addition)
# ════════════════════════════════════════════════════════════════════════════

# Drone movement order when shifting East: lead = most-East (slave_3 → slave_2 → slave_1)
# Drone movement order when shifting West: lead = most-West (slave_1 → slave_2 → slave_3)
# Middle drone moves after lead has ACKed its SIDE_MOVE.
# Trailing drone moves after middle has ACKed.
# This prevents any two drones from crossing X positions simultaneously.

SIDE_MOVE_DELAY_S = 2.0   # seconds to wait for each drone to settle before next

async def dispatch_side_move_ordered(
    connections: dict[str, "SlaveConnection"],
    direction:   str,   # "east" or "west"
    seq:         int = 0,
) -> bool:
    """
    Send SIDE_MOVE commands to slaves in lead→mid→tail order for the given
    shift direction.  Waits for each slave to ACK before commanding the next.

    Call this from start_tcp_commander's pass-transition logic, or from
    the voice bridge when a NEXT_PASS command is received.

    Returns True if all three slaves ACKed successfully.
    """
    # Determine order: lead is the drone already furthest in the move direction
    if direction == "east":
        # Shifting East: rightmost drone (slave_3) has most clearance → goes first
        order = ["slave_3", "slave_2", "slave_1"]
    else:
        # Shifting West: leftmost drone (slave_1) → goes first
        order = ["slave_1", "slave_2", "slave_3"]

    log.info(f"[SIDE_MOVE] direction={direction.upper()} order={order}")

    all_ok = True
    for drone_id in order:
        conn = connections.get(drone_id)
        if conn is None:
            log.warning(f"[SIDE_MOVE] No connection for {drone_id} — skipping")
            all_ok = False
            continue

        cmd = {"cmd": "SIDE_MOVE", "direction": direction, "seq": seq}
        log.info(f"[SIDE_MOVE] → {drone_id}  cmd={cmd}")

        try:
            ack = await conn.send_command(cmd, expect_ack=True)
            if ack.get("status") == "ok":
                log.info(f"[SIDE_MOVE] {drone_id} ACK — waiting {SIDE_MOVE_DELAY_S}s")
                await asyncio.sleep(SIDE_MOVE_DELAY_S)
            else:
                log.warning(f"[SIDE_MOVE] {drone_id} returned non-ok: {ack}")
                all_ok = False
        except Exception as e:
            log.error(f"[SIDE_MOVE] {drone_id} failed: {e}")
            all_ok = False

    log.info(f"[SIDE_MOVE] Complete — all_ok={all_ok}")
    return all_ok
